// angular-app/src/app/delete-person-form/delete-person-form.component.ts
import { Component } from '@angular/core';
import { PersonService } from '../person.service';

@Component({
  selector: 'app-delete-person-form',
  templateUrl: './delete-person-form.component.html',
  styleUrls: ['./delete-person-form.component.css'],
})
export class DeletePersonFormComponent {
  personId: number = 0;

  constructor(private personService: PersonService) {}

  onSubmit() {
    if (this.personId) {
      this.personService.deletePerson(this.personId).subscribe(
        (result) => {
          console.log('Osoba usunięta', result);
          window.location.href = '/';
        },
        (error) => {
          console.error('Wystąpił błąd podczas usuwania osoby', error);
        }
      );
    }
  }
}

<form (ngSubmit)="onSubmit()">
  <div>
    <label for="personId">ID osoby do usunięcia:</label>
    <input type="number" id="personId" [(ngModel)]="personId" name="personId" />
  </div>
  <button type="submit">Usuń osobę</button>
</form>

// react-app/src/DeletePersonForm.tsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'

const DeletePersonForm = () => {
  const navigate = useNavigate()
  const [personId, setPersonId] = useState('')

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      const response = await fetch(
        `https://localhost:7055/PersonDelete/${personId}`,
        {
          method: 'DELETE',
        }
      )

      if (response.ok) {
        navigate('/')
      }
    } catch (error) {
      console.error('Błąd podczas wysyłania żądania:', error)
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <label>
        ID osoby do usunięcia:
        <input
          type='text'
          value={personId}
          onChange={(e) => setPersonId(e.target.value)}
        />
      </label>
      <button type='submit'>Usuń osobę</button>
    </form>
  )
}

export default DeletePersonForm
